# Generated by Django 3.1.14 on 2022-06-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="status",
            field=models.CharField(
                choices=[("default", "default"), ("non active", "non active")],
                default="non active",
                max_length=15,
            ),
        ),
    ]
