# Generated by Django 3.1.14 on 2022-06-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_card_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="balance",
            field=models.FloatField(default=0),
        ),
    ]
