# Generated by Django 3.1.14 on 2022-06-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_auto_20220621_1946"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promocode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("sale", models.FloatField(default=0.1)),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("dead", "dead")],
                        default="active",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
