# Generated by Django 3.1.14 on 2022-06-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_auto_20220622_1457"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promocode",
            name="is_expired",
        ),
    ]
