# Generated by Django 3.1.14 on 2022-06-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_auto_20220623_1608"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="promocode",
        ),
        migrations.AddField(
            model_name="cart",
            name="promocode",
            field=models.CharField(blank=True, default="1", max_length=10, null=True),
        ),
    ]
